export class ConstHIVPerson {
  // STT
  static FULL_NAME = "fullName" // Họ và tên
  static BIRTH_DATE = "birthDate"// Năm sinh
  static GENDER = "gender"// Giới tính
  static OCCUPATION = "occupation"// Nghề nghiệp
  static GROUP = "group"// Nhóm đối tượng
  static RISK_BEHAVIORS = "riskBehaviors"// Hành vi nguy cơ
  static ETHNIC_EX = "ethnicEx"// Dân tộc
  static IDENTITY_NUMBER = "identityNumber"// Số CMND
  static INSURANCE_NR = "insuranceNr"// Số thẻ BHYT
  static TRANSMISSION_ROUTE = "transmissionRoute"// Đường lây nhiễm
  static SOURCE = "source"// Nguồn dịch vụ
  static PHONE_NUMBER = "phoneNumber"// Số điện thoại
  static PERMANENT_ADDRESS = "permanentAddress"// Số nhà thường trú
  static PERMANENT_ADDRESS_STRESS = "permanentAddressStress"// Đường phố thường trú
  static PERMANENT_ADDRESS_GROUP = "permanentAddressGroup"// Tổ/ấp/Khu phố thường trú
  static PERMANENT_COMMUNE = "permanentCommune"// Xã/Phường thường trú
  static PERMANENT_DISTRICT = "permanentDistrict"// Quận/Huyện thường trú
  static PERMANENT_PROVINCE = "permanentProvince"// Tỉnh/Thành thường trú
  static TEMPORAL_ADDRESS = "temporalAddress"// Số nhà cư trú
  static TEMPORAL_ADDRESS_STRESS = "temporalAddressStress"// Đường phố cư trú
  static TEMPORAL_ADDRESS_GROUP = "temporalAddressGroup"// Tổ/ấp/Khu phố cư trú
  static TEMPORAL_COMMUNE = "temporalCommune"// Xã/Phường cư trú
  static TEMPORAL_DISTRICT = "temporalDistrict"//  Quận/Huyện cư trú
  static TEMPORAL_PROVINCE = "temporalProvince"//  Tỉnh/Thành cư trú
  static PERMANENT_ADDRESS_STATUS = "permanentAddressStatus"//  Xác minh hiện trạng cư trú
  static HIV_CONFIRM_CODE = "hivConfirmCode"//  Mã XN khẳng định
  static CONFIRMATION_DATE = "confirmationDate"//  Ngày XN khẳng định 
  static RECENCY_DATE = "recencyDate"//  Ngày XN mới nhiễm 
  static HIV_STAGE_DATE = "hivStageDate"//  Ngày chẩn đoán lâm sàng 
  static CHANGE_TREATMEANT_DATE = "changeTreatmentDate"//  Ngày biến động điều trị
  static CONFIRM_LAB = "confirmLab"//  Cơ sở XN khẳng định 
  static SPECIMEN_COLLECTION_LAB = "specimenCollectionLab"//  Nơi lấy mẫu
  static RECENCY_RESULT = "recencyResult"//  Kết quả XN mới nhiễm
  static VL_RESULT = "vlResult"//  Kết quả XN tải lượng virus
  static VL_DATE = "vlDate"//  Ngày XN tải lượng virus
  static STATUS_OF_TREATMEANT = "statusOfTreatment"//  Trạng thái điều trị
  static START_TREATMENT_TIME = "startTreatmentTime"//  Ngày bắt đầu điều trị
  static PLACE_OF_TREATMEANT = "placeOfTreatment"//  Cơ sở điều trị
  static REGIMEN = "regimen"//  Phác đồ điều trị
  static FIRST_CD4 = "firstCd4"//  Kết quả XN CD4 lần đầu tiên
  static FIRST_CD4_DATE = "firstCd4Date"//  Ngày XN CD4 lần đầu tiên
  static CURRENT_CD4 = "currentCd4"//  Kết quả XN CD4 hiện tại
  static CURRENT_CD4_DATE = "currentCd4Date"//  Ngày XN CD4 lần gần đây nhất
  static FIRST_VL = "firstVl"//  Kết quả XN tải lượng virus lần đầu tiên
  static FIRST_VL_DATE = "firstVlDate"//  Ngày XN tải lượng virus lần đầu
  static CURRENT_VL = "currentVl"//  KQ XN tải lượng virus hiện tại
  static CURRENT_VL_DATE = "currentVlDate"//  Ngày XN tải lượng gần nhất
  static HIV_STAGE = "hivStage"//  Giai đoạn lâm sàng hiện tại
  static SYMPTOM = "symptom"//  Triệu chứng lâm sàng
  static OPC_CODE = "opcCode"//  Mã bệnh án
  static AIDS_STATUS = "aidsStatus"//  Tình trạng AIDS
  static AIDS_STATUS_DATE = "aidsStatusDate"//  Ngày chẩn đoán AIDS
  static STATUS_OF_CHANGE_TREATMEANT = "statusOfChangeTreatment"//  Trạng thái biến động điều trị
  static DEATH_REPORT_DATE = "deathReportDate"//  Ngày báo tử vong
  static DEATH_DATE = "deathDate"//  Ngày tử vong
  static DEATH_CAUSE = "deathCause"//  Nguyên nhân tử vong
  static NOTE = "note"//  Ghi chú
}
