export enum MENU {
  NN_CHUA_RA_SOAT = 1,
  NN_CAN_RA_SOAT = 2,
  NN_DA_RA_SOAT = 3,
  BIEN_DONG_DIEU_TRI = 4,
  NGUOI_NHIEM_NGOAI_TINH = 5,
  NGHI_TRUNG_NGOAI_TINH = 6,
  NGHI_TRUNG_NOI_TINH = 7,
  NGUOI_NHIEM_QUAN_LY = 8,
  DANH_SACH_NHIEM_MOI = 9,
  DANH_SACH_NGUOI_NHIEM_PHAT_HIEN = 10,
  DANH_SACH_NGUOI_NHIEM_TU_VONG = 11,
  DANH_SACH_BENH_NHAN_AIDS = 12,

}
export enum MenuTabManageInject {
  ALL = 1,
  DIFFERENT_PROVINCE = 2,
  ALIVE = 3,
  DEAD = 4,
  REQUEST_UPDATE_INFORMATION = 5,
  RE_REVIEW = 6,
  DELETED = 7
}
